#!/usr/bin/env bash

function parent_searcher()
{
    target=$1
    GREP_OPTIONS=
    classes=$(egrep -RI --include=*.h ".*class[ ]+\<$target\>[ ]*:" ./)
    #echo "> $classes"
    parent=$(echo $classes | sed -e 's;.*:\s\+\(public\|private\|protected\)\s\+\<\([A-Za-z][A-Za-z0-9_]*\)\>.*;\2;') 
    echo "$parent"
}

function searcher()
{
    parent=$(parent_searcher "$1")
    if [ "$parent" != "" ]
    then
        echo -en "$parent \e[1;32m>\e[0m "
        searcher "$parent"
    else
        echo -en "\e[1;31m|\e[0m"
    fi
}

echo -en "    \e[1;31m${1}\e[0m \e[1;32m:\e[0m "
searcher $1
echo
