#!/usr/bin/env bash

# Attach to a tmux interactively

# Define a few Color's
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NOCOL='\e[0m'              # No Color

# Prompt colors
PYELLOW='\[\e[1;33m\]'
PLIGHTRED='\[\e[1;31m\]'
PNOCOL='\[\e[0m\]'

set -e 

# Check for requirements
function checkRequiredProgram() {
    local program="$1"

    if ! command -v "${program}" &> /dev/null 
    then
        echo -e "Err: ${program} not found"
    fi
}


checkRequiredProgram fzf
checkRequiredProgram tmux


TMP_DIR=/tmp
sockets=$(ls $TMP_DIR/tmux-${UID}/)

chosenSession=$(echo "$sockets" | fzf -1 --preview='ses="$(tmux -L {} list-sessions 2>&1)" ; if [[ $ses =~ "no server running on" ]] ; then echo "\e[1;31mNo sessions \e[0m" ; else echo "\e[1;32m$ses\e[0m" ; fi' --no-input)
tmux -L $chosenSession new -A

