#!/usr/bin/env bash

# Download a video from youtube and convert it to mp4 or mkv

which yt-dlp
if [ $? -ne 0 ]; then
    echo "yt-dlp not found"
    echo -e "\tInstall it from your repo or grab a piece from https://github.com/yt-dlp/yt-dlp"
    exit 1
fi

# -a to batch download (one url per line)
# -N to specify the number of concurrent fragments (default 1) 

# "en.*" to get all english subtitles (en, en-US, en-GB, etc)
yt-dlp -t mp4 --write-subs --sub-langs 'en' --merge-output-format  mp4/mkv $*
